name: termchat_server CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "latest"
          otp-version: "latest"

      - name: Mix deps.get
        run: mix deps.get

      - name: Mix tests
        run: mix test
